2025-05-28 09:17:54 UTC
Windows-10-10.0.22621
Ren'Py 8.3.4.24120703

Early init took 0.06s
Loading error handling took 0.04s
Loading script took 0.59s
Loading save slot metadata took 0.03s
Loading persistent took 0.00s
Running init code took 0.08s
Loading analysis data took 0.01s
Analyze and compile ATL took 0.00s
Reloading save slot metadata took 0.02s
Index archives took 0.00s
Dump and make backups took 0.03s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc took 0.02s
DPI scale factor: 1.250000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: b'DRS_SaveSettings() = -1.' (can be ignored)
Creating interface object took 0.17s
Cleaning stores took 0.00s
Init translation took 0.02s
Build styles took 0.00s
Load screen analysis took 0.02s
Analyze screens took 0.00s
Save screen analysis took 0.00s
Prepare screens took 0.04s
Save pyanalysis. took 0.00s
Save bytecode. took 0.02s
Running _start took 0.00s
Interface start took 0.75s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: "b'NVIDIA Corporation'"
Renderer: b'NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2'
Version: b'4.6.0 NVIDIA 561.19'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1724, 970) drawable=(1724, 970)
Maximum texture size: 4096x4096
Exception in thread Thread-6:
Traceback (most recent call last):
  File "lib/python3.9/threading.py", line 973, in _bootstrap_inner
  File "lib/python3.9/threading.py", line 910, in run
  File "lib/python3.9/subprocess.py", line 1479, in _readerthread
  File "lib/python3.9/codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 116: invalid continuation byte
ASR Output (stdout): {"recognized_text": ""}
ASR Output (stderr): None
Recognized Text: 
Exception in thread Thread-9:
Traceback (most recent call last):
  File "lib/python3.9/threading.py", line 973, in _bootstrap_inner
  File "lib/python3.9/threading.py", line 910, in run
  File "lib/python3.9/subprocess.py", line 1479, in _readerthread
  File "lib/python3.9/codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 116: invalid continuation byte
ASR Output (stdout): {"recognized_text": "hello what's your name"}
ASR Output (stderr): None
Recognized Text: hello what's your name
AI Response Output (stdout): {"ai_response": "Hi! I'm Qwen, nice to meet you!"}

AI Response Output (stderr): 
TTS Output (stdout): Audio file generated at D:\renpy\myVN\myvn3\game\audio\temp_audio.mp3

TTS Output (stderr): 
