I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 148, in script
    pause 0.1
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 148, in script
    pause 0.1
  File "D:\renpy\renpy-8.3.4-sdk\renpy\execution.py", line 61, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-10-10.0.22621 AMD64
Ren'Py 8.3.4.24120703
myvn3 1.0
Wed Apr  9 20:57:43 2025
